### ISSUE TITLE
Unable to point to NGM dependency

### ISSUE THREAD

**Issue by BrianLohman** [t-neumann/slamdunk#65]
Hi,

I am trying to use slamdunk v 0.4.0, installed with conda -c bioconda. Broadly, I believe I have the same issue as #29 (missing NextGenMap). I manually installed NextGenMap (detailed here: https://github.com/Cibiv/NextGenMap/wiki/Installation), but I cannot figure out how to tell slamdunk where to find this new install. I would add the symlink to ```slamdunk/slamdunk/contrib```, as in #29, but that directory does not exist. 

I don't suppose there is a global config file I can edit? Adding the new install of ngm to my path does not work. Any ideas would be welcome. 

Cheers,

Brian 

```
slamdunk all \
    ./Fastq/17503X1_191219_A00421_0139_AHL5WCDMXX_S8_L001_R*_001.clump.fastq.gz \
    -t 12 \
    -o ./slam_dunk_results \
    -b ./Mus_musculus.GRCm38.98.3primeUTR.bed \
    -r /tomato/dev/data/Mouse/GRCm38/release99/Mus_musculus.GRCm38.dna.primary_assembly.fa

slamdunk all
Running slamDunk map for 2 files (12 threads)
Traceback (most recent call last):
  File "/home/u0806040/anaconda3/bin/slamdunk", line 10, in <module>
    sys.exit(run())
  File "/home/u0806040/anaconda3/lib/python3.7/site-packages/slamdunk/slamdunk.py", line 478, in run
    runAll(args)
  File "/home/u0806040/anaconda3/lib/python3.7/site-packages/slamdunk/slamdunk.py", line 233, in runAll
    runMap(tid, bam, referenceFile, n, args.trim5, args.maxPolyA, args.quantseq, args.endtoend, args.topn, sampleInfo, dunkPath, args.skipSAM)
  File "/home/u0806040/anaconda3/lib/python3.7/site-packages/slamdunk/slamdunk.py", line 148, in runMap
    mapper.Map(inputBAM, referenceFile, outputSAM, getLogFile(outputLOG), quantseqMapping, endtoendMapping, threads=threads, trim5p=trim5p, maxPolyA=maxPolyA, topn=topn, sampleId=tid, sampleName=sampleName, sampleType=sampleType, sampleTime=sampleTime, printOnly=printOnly, verbose=verbose)
  File "/home/u0806040/anaconda3/lib/python3.7/site-packages/slamdunk/dunks/mapper.py", line 104, in Map
    run("ngm -r " + inputReference + " -q " + inputBAM + " -t " + str(threads) + " " + parameter + " -o " + outputSAM, log, verbose=verbose, dry=printOnly)
  File "/home/u0806040/anaconda3/lib/python3.7/site-packages/slamdunk/utils/misc.py", line 196, in run
    raise RuntimeError("Error while executing command: \"" + cmd + "\"")
RuntimeError: Error while executing command: "ngm -r /tomato/dev/data/Mouse/GRCm38/release98/Mus_musculus.GRCm38.dna.primary_assembly.fa -q ./Fastq/17503X1_191219_A00421_0139_AHL5WCDMXX_S8_L001_R1_001.clump.fastq.gz -t 12 --no-progress --slam-seq 2 -5 12 --max-polya 4 -l  --rg-id 0 --rg-sm sample_0:NA:-1 -o ./slam_dunk_results/map/17503X1_191219_A00421_0139_AHL5WCDMXX_S8_L001_R1_001.clump.fastq_slamdunk_mapped.sam"

(base)$ which ngm
~/src/NextGenMap-0.5.2/bin/ngm-0.5.2/ngm
```

**Comment by t-neumann** [comment]
Hi Brian! I am currently on holiday, so it's a bit tough to run diagnostics here. I recently refactored Slamdunk so all external dependencies such as NextGenMap should be pulled directly from Bioconda when you install Slamdunk from Bioconda since they are listed as dependencies. Did they pop up to be installed when you did `conda install slamdunk`? Second, did you also check the log files in the map subfolder? Do they explicitely say it is missing `ngm` or is there some other error?

**Comment by BrianLohman** [comment]
Hi Tobias,

Thanks for your quick reply.

Here is what happens when I try to install from bioconda. I don't see NGM in the list of additional packages to install. It's possible that it's a conda error (note the several failures by the solver)

```
(base) [u0806040@hci-uinta ~]$ conda install slamdunk -c bioconda
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/u0806040/anaconda3

  added / updated specs:
    - slamdunk


The following NEW packages will be INSTALLED:

  _r-mutex           pkgs/r/linux-64::_r-mutex-1.0.0-anacondar_1
  bedtools           bioconda/linux-64::bedtools-2.29.2-hc088bd4_0
  binutils_impl_lin~ pkgs/main/linux-64::binutils_impl_linux-64-2.33.1-he6710b0_7
  binutils_linux-64  pkgs/main/linux-64::binutils_linux-64-2.33.1-h9595d00_15
  biopython          pkgs/main/linux-64::biopython-1.74-py37h7b6447c_0
  bwidget            pkgs/main/linux-64::bwidget-1.9.11-1
  gcc_impl_linux-64  pkgs/main/linux-64::gcc_impl_linux-64-7.3.0-habb00fd_1
  gcc_linux-64       pkgs/main/linux-64::gcc_linux-64-7.3.0-h553295d_15
  gfortran_impl_lin~ pkgs/main/linux-64::gfortran_impl_linux-64-7.3.0-hdf63c60_1
  gfortran_linux-64  pkgs/main/linux-64::gfortran_linux-64-7.3.0-h553295d_15
  gsl                pkgs/main/linux-64::gsl-2.4-h14c3975_4
  gxx_impl_linux-64  pkgs/main/linux-64::gxx_impl_linux-64-7.3.0-hdf63c60_1
  gxx_linux-64       pkgs/main/linux-64::gxx_linux-64-7.3.0-h553295d_15
  intervaltree       pkgs/main/noarch::intervaltree-3.0.2-py_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libdeflate         bioconda/linux-64::libdeflate-1.0-h14c3975_1
  make               pkgs/main/linux-64::make-4.2.1-h1bed415_1
  pybedtools         bioconda/linux-64::pybedtools-0.8.1-py37he513fc3_0
  pysam              bioconda/linux-64::pysam-0.15.3-py37hda2845c_1
  r-askpass          pkgs/r/linux-64::r-askpass-1.0-r36h14c3975_0
  r-assertthat       pkgs/r/noarch::r-assertthat-0.2.1-r36h6115d3f_0
  r-backports        pkgs/r/linux-64::r-backports-1.1.4-r36h96ca727_0
  r-base             pkgs/r/linux-64::r-base-3.6.1-h9bb98a2_1
  r-base64enc        pkgs/r/linux-64::r-base64enc-0.1_3-r36h96ca727_4
  r-bh               pkgs/r/noarch::r-bh-1.69.0_1-r36h6115d3f_0
  r-broom            pkgs/r/noarch::r-broom-0.5.2-r36h6115d3f_0
  r-callr            pkgs/r/noarch::r-callr-3.2.0-r36h6115d3f_0
  r-cellranger       pkgs/r/noarch::r-cellranger-1.1.0-r36h6115d3f_0
  r-cli              pkgs/r/noarch::r-cli-1.1.0-r36h6115d3f_0
  r-clipr            pkgs/r/noarch::r-clipr-0.6.0-r36h6115d3f_0
  r-colorspace       pkgs/r/linux-64::r-colorspace-1.4_1-r36h96ca727_0
  r-crayon           pkgs/r/noarch::r-crayon-1.3.4-r36h6115d3f_0
  r-curl             pkgs/r/linux-64::r-curl-3.3-r36h96ca727_0
  r-dbi              pkgs/r/noarch::r-dbi-1.0.0-r36h6115d3f_0
  r-dbplyr           pkgs/r/noarch::r-dbplyr-1.4.0-r36h6115d3f_0
  r-dichromat        pkgs/r/noarch::r-dichromat-2.0_0-r36h6115d3f_4
  r-digest           pkgs/r/linux-64::r-digest-0.6.18-r36h96ca727_0
  r-dplyr            pkgs/r/linux-64::r-dplyr-0.8.0.1-r36h29659fb_0
  r-ellipsis         pkgs/r/linux-64::r-ellipsis-0.1.0-r36h96ca727_0
  r-evaluate         pkgs/r/noarch::r-evaluate-0.13-r36h6115d3f_0
  r-fansi            pkgs/r/linux-64::r-fansi-0.4.0-r36h96ca727_0
  r-forcats          pkgs/r/noarch::r-forcats-0.4.0-r36h6115d3f_0
  r-fs               pkgs/r/linux-64::r-fs-1.2.7-r36h29659fb_0
  r-generics         pkgs/r/noarch::r-generics-0.0.2-r36h6115d3f_0
  r-ggplot2          pkgs/r/noarch::r-ggplot2-3.1.1-r36h6115d3f_0
  r-glue             pkgs/r/linux-64::r-glue-1.3.1-r36h96ca727_0
  r-gtable           pkgs/r/noarch::r-gtable-0.3.0-r36h6115d3f_0
  r-haven            pkgs/r/linux-64::r-haven-2.1.0-r36h29659fb_0
  r-highr            pkgs/r/noarch::r-highr-0.8-r36h6115d3f_0
  r-hms              pkgs/r/noarch::r-hms-0.4.2-r36h6115d3f_0
  r-htmltools        pkgs/r/linux-64::r-htmltools-0.3.6-r36h29659fb_0
  r-httr             pkgs/r/noarch::r-httr-1.4.0-r36h6115d3f_0
  r-jsonlite         pkgs/r/linux-64::r-jsonlite-1.6-r36h96ca727_0
  r-knitr            pkgs/r/noarch::r-knitr-1.22-r36h6115d3f_0
  r-labeling         pkgs/r/noarch::r-labeling-0.3-r36h6115d3f_4
  r-lattice          pkgs/r/linux-64::r-lattice-0.20_38-r36h96ca727_0
  r-lazyeval         pkgs/r/linux-64::r-lazyeval-0.2.2-r36h96ca727_0
  r-lubridate        pkgs/r/linux-64::r-lubridate-1.7.4-r36h29659fb_0
  r-magrittr         pkgs/r/noarch::r-magrittr-1.5-r36h6115d3f_4
  r-markdown         pkgs/r/linux-64::r-markdown-0.9-r36h96ca727_0
  r-mass             pkgs/r/linux-64::r-mass-7.3_51.3-r36h96ca727_0
  r-matrix           pkgs/r/linux-64::r-matrix-1.2_17-r36h96ca727_0
  r-mgcv             pkgs/r/linux-64::r-mgcv-1.8_28-r36h96ca727_0
  r-mime             pkgs/r/linux-64::r-mime-0.6-r36h96ca727_0
  r-modelr           pkgs/r/noarch::r-modelr-0.1.4-r36h6115d3f_0
  r-munsell          pkgs/r/noarch::r-munsell-0.5.0-r36h6115d3f_0
  r-nlme             pkgs/r/linux-64::r-nlme-3.1_139-r36ha65eedd_0
  r-openssl          pkgs/r/linux-64::r-openssl-1.3-r36h96ca727_0
  r-pillar           pkgs/r/noarch::r-pillar-1.3.1-r36h6115d3f_0
  r-pkgconfig        pkgs/r/noarch::r-pkgconfig-2.0.2-r36h6115d3f_0
  r-plogr            pkgs/r/noarch::r-plogr-0.2.0-r36h6115d3f_0
  r-plyr             pkgs/r/linux-64::r-plyr-1.8.4-r36h29659fb_0
  r-prettyunits      pkgs/r/noarch::r-prettyunits-1.0.2-r36h6115d3f_0
  r-processx         pkgs/r/linux-64::r-processx-3.3.0-r36h96ca727_0
  r-progress         pkgs/r/noarch::r-progress-1.2.0-r36h6115d3f_0
  r-ps               pkgs/r/linux-64::r-ps-1.3.0-r36h96ca727_0
  r-purrr            pkgs/r/linux-64::r-purrr-0.3.2-r36h96ca727_0
  r-r6               pkgs/r/noarch::r-r6-2.4.0-r36h6115d3f_0
  r-rcolorbrewer     pkgs/r/noarch::r-rcolorbrewer-1.1_2-r36h6115d3f_0
  r-rcpp             pkgs/r/linux-64::r-rcpp-1.0.1-r36h29659fb_0
  r-readr            pkgs/r/linux-64::r-readr-1.3.1-r36h29659fb_0
  r-readxl           pkgs/r/linux-64::r-readxl-1.3.1-r36h29659fb_0
  r-rematch          pkgs/r/noarch::r-rematch-1.0.1-r36h6115d3f_0
  r-reprex           pkgs/r/noarch::r-reprex-0.2.1-r36h6115d3f_0
  r-reshape2         pkgs/r/linux-64::r-reshape2-1.4.3-r36h29659fb_0
  r-rlang            pkgs/r/linux-64::r-rlang-0.3.4-r36h96ca727_0
  r-rmarkdown        pkgs/r/noarch::r-rmarkdown-1.12-r36h6115d3f_0
  r-rstudioapi       pkgs/r/noarch::r-rstudioapi-0.10-r36h6115d3f_0
  r-rvest            pkgs/r/noarch::r-rvest-0.3.3-r36h6115d3f_0
  r-scales           pkgs/r/linux-64::r-scales-1.0.0-r36h29659fb_0
  r-selectr          pkgs/r/noarch::r-selectr-0.4_1-r36h6115d3f_0
  r-stringi          pkgs/r/linux-64::r-stringi-1.4.3-r36h29659fb_0
  r-stringr          pkgs/r/noarch::r-stringr-1.4.0-r36h6115d3f_0
  r-sys              pkgs/r/linux-64::r-sys-3.2-r36h96ca727_0
  r-tibble           pkgs/r/linux-64::r-tibble-2.1.1-r36h96ca727_0
  r-tidyr            pkgs/r/linux-64::r-tidyr-0.8.3-r36h29659fb_0
  r-tidyselect       pkgs/r/linux-64::r-tidyselect-0.2.5-r36h29659fb_0
  r-tidyverse        pkgs/r/noarch::r-tidyverse-1.2.1-r36h6115d3f_0
  r-tinytex          pkgs/r/noarch::r-tinytex-0.12-r36h6115d3f_0
  r-utf8             pkgs/r/linux-64::r-utf8-1.1.4-r36h96ca727_0
  r-viridislite      pkgs/r/noarch::r-viridislite-0.3.0-r36h6115d3f_0
  r-whisker          pkgs/r/noarch::r-whisker-0.3_2-r36h6115d3f_4
  r-withr            pkgs/r/noarch::r-withr-2.1.2-r36h6115d3f_0
  r-xfun             pkgs/r/noarch::r-xfun-0.6-r36h6115d3f_0
  r-xml2             pkgs/r/linux-64::r-xml2-1.2.0-r36h29659fb_0
  r-yaml             pkgs/r/linux-64::r-yaml-2.2.0-r36h96ca727_0
  slamdunk           bioconda/noarch::slamdunk-0.4.0-py_0
  tktable            pkgs/main/linux-64::tktable-2.10-h14c3975_0


Proceed ([y]/n)?
```

There are two log files in ```slam_dunk_results/map```

```
cat 17503X1_191219_A00421_0139_AHL5WCDMXX_S8_L001_R1_001.clump.fastq_slamdunk_mapped.log
b'/bin/sh: ngm: command not found\n'b'/bin/sh: ngm: command not found\n'b'/bin/sh: ngm: command not found\n'b'/bin/sh: ngm: command not found\n'b'/bin/sh: ngm: command not found\n'b'/bin/sh: ngm: command not found\n'b'[MAIN] NextGenMap 0.5.2\n'b'[MAIN] Startup : x64 (build Jan 10 2020 11:13:18)\n'b'[MAIN] Starting time: 2020-01-10.11:52:45\n'b'[CONFIG] Parameter:  --affine 0 --argos_min_score 0 --bin_size 2 --block_multiplier 2 --bs_cutoff 6 --bs_mapping 0 --cpu_threads 12 --dualstrand 1 --fast 0 --fast_pairing 0 --force_rlength_check 0 --format 1 --gap_extend_penalty 5 --gap_read_penalty 20 --gap_ref_penalty 20 --hard_clip 0 --keep_tags 0 --kmer 13 --kmer_min 0 --kmer_skip 2 --local 1 --match_bonus 10 --match_bonus_tc 2 --match_bonus_tt 10 --max_cmrs 2147483647 --max_equal 1 --max_insert_size 1000 --max_polya 4 --max_read_length 0 --min_identity 0.650000 --min_insert_size 0 --min_mq 0 --min_residues 0.500000 --min_score 0.000000 --mismatch_penalty 15 --mode 0 --no_progress 1 --no_unal 0 --ocl_threads 1 --output ./slam_dunk_results/map/17503X1_191219_A00421_0139_AHL5WCDMXX_S8_L001_R1_001.clump.fastq_slamdunk_mapped.sam --overwrite 1 --pair_score_cutoff 0.900000 --paired 0 --parse_all 1 --pe_delimiter / --qry ./Fastq/17503X1_191219_A00421_0139_AHL5WCDMXX_S8_L001_R1_001.clump.fastq.gz --qry_count -1 --qry_start 0 --ref /tomato/dev/data/Mouse/GRCm38/release98/Mus_musculus.GRCm38.dna.primary_assembly.fa --ref_mode -1 --rg_id 0 --rg_sm sample_0:NA:-1 --sensitive 0 --silent_clip 0 --skip_mate_check 0 --skip_save 0 --slam_seq 2 --step_count 4 --strata 0 --topn 1 --trim5 12 --update_check 0 --very_fast 0 --very_sensitive 0\n'b'[NGM] Opening for output (SAM): ./slam_dunk_results/map/17503X1_191219_A00421_0139_AHL5WCDMXX_S8_L001_R1_001.clump.fastq_slamdunk_mapped.sam\n'b'[SEQPROV] Encoding reference sequence.\n'b'[SEQPROV] Size of reference genome 2730 Mbp (max. 17179 Mbp)\n'b'[SEQPROV] Allocating 1365469438 (2776390504) bytes for the reference.\n'b'[SEQPROV] BinRef length: 1365469403ll (elapsed 13.125677)\n'b'[SEQPROV] 0 reference sequences were skipped (length < 10).\n'b'[SEQPROV] Writing encoded reference to /tomato/dev/data/Mouse/GRCm38/release98/Mus_musculus.GRCm38.dna.primary_assembly.fa-enc.2.ngm\n'b'[MAIN] NextGenMap 0.5.2\n'b'[MAIN] Startup : x64 (build Jan 10 2020 11:13:18)\n'b'[MAIN] Starting time: 2020-01-13.10:27:01\n'b'[CONFIG] Parameter:  --affine 0 --argos_min_score 0 --bin_size 2 --block_multiplier 2 --bs_cutoff 6 --bs_mapping 0 --cpu_threads 12 --dualstrand 1 --fast 0 --fast_pairing 0 --force_rlength_check 0 --format 1 --gap_extend_penalty 5 --gap_read_penalty 20 --gap_ref_penalty 20 --hard_clip 0 --keep_tags 0 --kmer 13 --kmer_min 0 --kmer_skip 2 --local 1 --match_bonus 10 --match_bonus_tc 2 --match_bonus_tt 10 --max_cmrs 2147483647 --max_equal 1 --max_insert_size 1000 --max_polya 4 --max_read_length 0 --min_identity 0.650000 --min_insert_size 0 --min_mq 0 --min_residues 0.500000 --min_score 0.000000 --mismatch_penalty 15 --mode 0 --no_progress 1 --no_unal 0 --ocl_threads 1 --output ./slam_dunk_results/map/17503X1_191219_A00421_0139_AHL5WCDMXX_S8_L001_R1_001.clump.fastq_slamdunk_mapped.sam --overwrite 1 --pair_score_cutoff 0.900000 --paired 0 --parse_all 1 --pe_delimiter / --qry ./Fastq/17503X1_191219_A00421_0139_AHL5WCDMXX_S8_L001_R1_001.clump.fastq.gz --qry_count -1 --qry_start 0 --ref /tomato/dev/data/Mouse/GRCm38/release98/Mus_musculus.GRCm38.dna.primary_assembly.fa --ref_mode -1 --rg_id 0 --rg_sm sample_0:NA:-1 --sensitive 0 --silent_clip 0 --skip_mate_check 0 --skip_save 0 --slam_seq 2 --step_count 4 --strata 0 --topn 1 --trim5 12 --update_check 0 --very_fast 0 --very_sensitive 0\n'b'[NGM] Opening for output (SAM): ./slam_dunk_results/map/17503X1_191219_A00421_0139_AHL5WCDMXX_S8_L001_R1_001.clump.fastq_slamdunk_mapped.sam\n'b'[SEQPROV] Encoding reference sequence.\n'b'[SEQPROV] Size of reference genome 2730 Mbp (max. 17179 Mbp)\n'b'[SEQPROV] Allocating 1365469438 (2776390504) bytes for the reference.\n'b'[SEQPROV] BinRef length: 1365469403ll (elapsed 11.049130)\n'b'[SEQPROV] 0 reference sequences were skipped (length < 10).\n'b'[SEQPROV] Writing encoded reference to /tomato/dev/data/Mouse/GRCm38/release98/Mus_musculus.GRCm38.dna.primary_assembly.fa-enc.2.ngm\n'(base) [u0806040@hci-uinta map]$ less -S 17503X1_191219_A00421_0139_AHL5WCDMXX_S8_L001_R1_001.clump.fastq_slamdunk_mapped.log
```

and 

```
cat samples_slamdunk_mapped.log
b'/bin/sh: ngm: command not found\n'b'/bin/sh: ngm: command not found\n'
```

**Comment by t-neumann** [comment]
Hm can you try 2 things:

1) Make sure the conda channels are setup in the right order:

```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

2) Wipe your environment and create a clean one:

```
conda create --name slamdunk slamdunk
```

Because I see you are still on slamdunk v0.4.0 when the newest one should be 0.4.1.

Also if you look [here](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/slamdunk/meta.yaml) clearly NextGenMap is listed as dependency, so I don't exactly know why it is not listed in your packages list.

**Comment by BrianLohman** [comment]
Hi Tobias,

Thank you for your continued help. I set the conda channels as you suggested and then reinstalled. This still pulled down v 0.4.0. Next I rebuilt the environment as you suggested. This retrieved 0.4.1 and NGM 

```
(slamdunk) $ slamdunk --version
slamdunk 0.4.1
(slamdunk) $ which slamdunk
~/anaconda3/envs/slamdunk/bin/slamdunk
(slamdunk) $ which ngm
~/anaconda3/envs/slamdunk/bin/ngm
```
However, I still get the same error. The stdout produces the same message and the log file (*clump.fastq_slamdunk_mapped.log) has the same error message as well. This time samples_slamdunk_mapped.log was not written. 


If i try ```slamdunk map``` by itself I get:

```
slamdunk map /Fastq/17503X1_191219_A00421_0139_AHL5WCDMXX_S8_L001_R1_001.clump.fastq.gz /Fastq/17503X1_191219_A00421_0139_AHL5WCDMXX_S8_L001_R2_001.clump.fastq.gz -r /tomato/dev/data/Mouse/GRCm38/release98/Mus_musculus.GRCm38.dna.primary_assembly.fa -o test

Traceback (most recent call last):
  File "/home/u0806040/anaconda3/envs/slamdunk/bin/slamdunk", line 10, in <module>
    sys.exit(run())
  File "/home/u0806040/anaconda3/envs/slamdunk/lib/python3.6/site-packages/slamdunk/slamdunk.py", line 414, in run
    mapper.checkNextGenMapVersion()
  File "/home/u0806040/anaconda3/envs/slamdunk/lib/python3.6/site-packages/slamdunk/dunks/mapper.py", line 37, in checkNextGenMapVersion
    matchObj = re.match( r'.*([0-9]+\.[0-9]+\.[0-9]+).*', ngmHelp, re.M|re.I)
  File "/home/u0806040/anaconda3/envs/slamdunk/lib/python3.6/re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: cannot use a string pattern on a bytes-like object

```

Thank you for your assistance. 

Cheers,

Brian

**Comment by t-neumann** [comment]
Sorry @BrianLohman for digging this up just now - it got lost while I was on holiday.

The problem does not occur in the slamdunk all command, but if you run `map` individually, I also experienced this. This is a leftover from the py2 to py3 conversion and I will fix that with the next release.

**Comment by bsennblad** [comment]
@t-neumann : I ran into the latter problem, i.e., "TypeError: cannot use a string pattern on a bytes-object" (due to Popen,communicate() returning a byte object rather than a string) when using the 0.4.1 conda package in a project. I see that the issue already seems to be fixed in the latest Github code. Do you have any estimate for when a new release (and specifically a conda package of the release) will be done?
Thanks for a great software!

**Comment by t-neumann** [comment]
New build is out.
