### ISSUE TITLE
'sys' has no attribute 'maxint'

### ISSUE THREAD

**Issue by BrianLohman** [t-neumann/slamdunk#66]
Hi Tobias,

I was able to avoid the issues with #65 by using the Docker image you have on Docker Hub. Thank you for providing that.  However, I have encountered a new error. The stdout looks like:

```
slamdunk all
Running slamDunk map for 2 files (12 threads)
..
Running slamDunk sam2bam for 2 files (12 threads)
..
Creating output directory: ./slam_dunk_results/filter
Running slamDunk filter for 2 files (12 threads)


Creating output directory: ./slam_dunk_results/snp
Running slamDunk SNP for 2 files (6 threads)
..
Creating output directory: ./slam_dunk_results/count
Running slamDunk tcount for 2 files (12 threads)
..joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 600, in __call__
    return self.func(*args, **kwargs)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/slamdunk.py", line 189, in runCount
    maxLength = estimateMaxReadLength(bam)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/utils/misc.py", line 95, in estimateMaxReadLength
    minLength = sys.maxint
AttributeError: module 'sys' has no attribute 'maxint'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/slamdunk/bin/slamdunk", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/slamdunk.py", line 478, in run
    runAll(args)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/slamdunk.py", line 309, in runAll
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runCount)(tid, dunkbufferIn[tid], referenceFile, args.bed, args.maxLength, args.minQual, args.conversionThreshold, dunkPath, snpDirectory) for tid in range(0, len(samples)))
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 1016, in __call__
    self.retrieve()
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 908, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 554, in wrap_future_result
    return future.result(timeout=timeout)
  File "/opt/conda/envs/slamdunk/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/opt/conda/envs/slamdunk/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
AttributeError: module 'sys' has no attribute 'maxint'
```

which looks like it could be a python 2 vs 3 problem:
https://stackoverflow.com/questions/13795758/what-is-sys-maxint-in-python-3

Cheers,

Brian

**Comment by t-neumann** [comment]
Hi Brian,

indeed it looks like this is a bug - can you send me the command line call you use?

I suspect you do not provide the max read length and therefore run into troubles here.

**Comment by BrianLohman** [comment]
Hi Tobias,

You are correct, I was not specifying the max read length. I ran:

```
slamdunk all \
    ./Fastq/17503X1_191219_A00421_0139_AHL5WCDMXX_S8_L001_R*_001.clump.fastq.gz \
    -t 12 \
    -o ./slam_dunk_results \
    -b ./Mus_musculus.GRCm38.98.3primeUTR.bed \
    -r ./Mus_musculus.GRCm38.dna.primary_assembly.fa
```

I added the -rl flag to get:
```
slamdunk all \
    ./Fastq/17503X1_191219_A00421_0139_AHL5WCDMXX_S8_L001_R*_001.clump.fastq.gz \
    -t 12 \
    -o ./slam_dunk_results \
    -rl 150 \
    -b ./Mus_musculus.GRCm38.98.3primeUTR.bed \
    -r ./Mus_musculus.GRCm38.dna.primary_assembly.fa
```

and reran. Slamdunk used chached results for map, sam2bam, filter, and SNP, but tcount failed with:
```
slamdunk all
Running slamDunk map for 2 files (12 threads)
..
Running slamDunk sam2bam for 2 files (12 threads)
..
Running slamDunk filter for 2 files (12 threads)


Running slamDunk SNP for 2 files (6 threads)
..
Running slamDunk tcount for 2 files (12 threads)
..joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 600, in __call__
    return self.func(*args, **kwargs)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/slamdunk.py", line 198, in runCount
    tcounter.computeTconversions(ref, bed, inputSNP, bam, maxLength, minQual, outputCSV, outputBedgraphPlus, outputBedgraphMinus, conversionThreshold, log)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/dunks/tcounter.py", line 165, in computeTconversions
    for utr in BedIterator(bed):
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/utils/BedReader.py", line 81, in __next__
    return self._toBED(self._bedFile.__next__())
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/utils/BedReader.py", line 67, in _toBED
    bedEntry.start = int(cols[1])
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/slamdunk/bin/slamdunk", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/slamdunk.py", line 478, in run
    runAll(args)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/slamdunk.py", line 309, in runAll
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runCount)(tid, dunkbufferIn[tid], referenceFile, args.bed, args.maxLength, args.minQual, args.conversionThreshold, dunkPath, snpDirectory) for tid in range(0, len(samples)))
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 1016, in __call__
    self.retrieve()
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 908, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 554, in wrap_future_result
    return future.result(timeout=timeout)
  File "/opt/conda/envs/slamdunk/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/opt/conda/envs/slamdunk/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
IndexError: list index out of range
```

Thank you for your continued assistance. 

Cheers,

Brian

**Comment by t-neumann** [comment]
Hm seems to be a problem with the bed-file format. Could you send it over to check?

**Comment by BrianLohman** [comment]
Hi Tobias,

I am using the 3 column bed format. I have attached the file. 

Cheers,

Brian 

[Mus_musculus.GRCm38.98.3primeUTR.bed.gz](https://github.com/t-neumann/slamdunk/files/4078581/Mus_musculus.GRCm38.98.3primeUTR.bed.gz)

**Comment by t-neumann** [comment]
Ok you need a 6 column bed file including strand information, since the SLAMseq assay is stranded. That should solve this.

**Comment by BrianLohman** [comment]
Hi Tobias,

I have added the extra information to the BED file and the tcount function now successfully completes. Thanks for your patience. 

Cheers,

Brian
