### ISSUE TITLE
error in alleyoop merge

### ISSUE THREAD

**Issue by BrianLohman** [t-neumann/slamdunk#68]
Hi Tobias,

I have having problems merging samples into a single count table with alleyoop merge. I have run 

1) slamdunk all
2) alleyoop collapse

I am trying to merge with:
```
alleyoop merge -o counts.csv 17503X*_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv 
```

in a directory that contains only the products of the prior collapse function (.csvs and .logs) 

The error is get is:
```
Running alleyoop merge for 8 files
Traceback (most recent call last):
  File "/opt/conda/envs/slamdunk/bin/alleyoop", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/alleyoop.py", line 506, in run
    stats.mergeRates(",".join(args.countFiles), args.outputFile, args.column, args.columnName, getLogFile(outputLog))
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/dunks/stats.py", line 856, in mergeRates
    callR(cmd, log, dry=printOnly, verbose=verbose)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/utils/misc.py", line 211, in callR
    raise RuntimeError("Error while executing command: \"" + cmd + "\"")
RuntimeError: Error while executing command: "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/plot/merge_rate_files.R -f 17503X1_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv,17503X2_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv,17503X3_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv,17503X4_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv,17503X5_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv,17503X6_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv,17503X7_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv,17503X8_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv -o counts.csv -c "TcReadCount / ReadCount" -n 2"
```

counts.log contains:
```
/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/plot/merge_rate_files.R -f 17503X1_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv,17503X2_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv,17503X3_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv,17503X4_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv,17503X5_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv,17503X6_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv,17503X7_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv,17503X8_R1_R2.fastq_slamdunk_mapped_filtered_tcount_collapsed.csv -o counts.csv -c "TcReadCount / ReadCount" -n 2
b'Error in eval(parse(text = evalExpression)) : \n'b"  object 'TcReadCount' not found\n"b'Calls: eval -> eval\n'b'In addition: Warning message:\n'b'In as.numeric(meta[1]) : NAs introduced by coercion\n'b'Execution halted\n'(slamdunk)
```

The head of the first tcount file looks like:
```
gene_name	length	readsCPM	conversionRate	Tcontent	coverageOnTs	conversionsOnTs	readCount	tcReadCount	multimapCount
ENSMUSG00000000001	2054	124.06274190104055	0.0011761034971077455	710	41663	49	1019	38	0
ENSMUSG00000000003	469	0.0	0	186	0	0	0	0	0
ENSMUSG00000000028	248	1.2174950137491711	0.0	102	142	0	10	2	0
ENSMUSG00000000037	6204	0.36524850412475135	0.0	2340	177	0	3	0	0
ENSMUSG00000000049	100	0.0	0	36	0	0	0	0	0
ENSMUSG00000000056	2933	26.906639803856685	0.0006960879855213699	772	7183	5	221	5	0
ENSMUSG00000000058	3001	280.1456026636843	0.0019204275038617292	1013	95812	184	2301	134	2
ENSMUSG00000000078	3862	317.8879480899086	0.0004310163575964005	1163	95124	41	2611	42	4
ENSMUSG00000000085	1488	24.83689828048309	0.001981178801386825	390	6057	12	204	10	0
```
Thanks for your help,

Brian

**Comment by t-neumann** [comment]
Hi @BrianLohman ,

I had a look and apparently I never tried it in collapsed files. It works on the plain count files, but some columns are missing / named differently in the collapsed files and that is what causes `alleyoop merge` to fail.

Depending on how urgently you need this fixed, you can either wait for me to fix this which might be not be before the end of the week or submit your own PR.

**Comment by BrianLohman** [comment]
Hi Tobias,

I tried running ```alleyoop merge``` before running ```alleyoop collapse``` but I got the following error:

```
alleyoop merge -o counts.csv /tomato/dev/job/lohman/A6097/single_end/count/17503X*_R1_R2.fastq_slamdunk_mapped_filtered_tcount.tsv 
Running alleyoop merge for 8 files

alleyoop collapse -o collapsed_counts.csv counts.csv
Creating output directory: collapsed_counts.csv
Running alleyoop collapse for 1 files (1 threads)
Traceback (most recent call last):
  File "/home/u0806040/anaconda3/bin/alleyoop", line 10, in <module>
    sys.exit(run())
  File "/home/u0806040/anaconda3/lib/python3.7/site-packages/slamdunk/alleyoop.py", line 426, in run
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runCollapse)(tid, args.tcount[tid], outputDirectory) for tid in range(0, len(args.tcount)))
  File "/home/u0806040/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/u0806040/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/u0806040/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/home/u0806040/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/home/u0806040/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/home/u0806040/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/u0806040/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/u0806040/anaconda3/lib/python3.7/site-packages/slamdunk/alleyoop.py", line 98, in runCollapse
    tcounter.collapse(tcount, outputTCOUNT, log)
  File "/home/u0806040/anaconda3/lib/python3.7/site-packages/slamdunk/dunks/tcounter.py", line 82, in collapse
    tcDict[gene]['coverageOnTs'] = max(int(coverageOnTs),0)
ValueError: invalid literal for int() with base 10: '163.875'
```
the counts table (product of ```alleyoop merge```) look good, but still needs to be collapsed (transcripts to genes). 

I can write a little work around, but I'm not confident it would be suitable to add to your package. 

Thanks for your help,

Brian

**Comment by t-neumann** [comment]
Hi Brian,

yes the collapse file format is slightly different from the count ones, so `merge` won't work on it. Similarly, `collapse` does not work on the file format produced by `merge`.

The proper way to resolve this would be to rewrite the file format of `collapse` to have the same number of columns and column names as the original `count` files and then `merge` should work fine.

Again, I would be happy to help you with fixing the `collapse` function if you think you can pull off a PR, otherwise it might take some time until I can get to it myself.

Cheers,

Tobi
