### ISSUE TITLE
Permission denied trying to run globalRatePlotter.R

### ISSUE THREAD

**Issue by FitzsimmonsCM** [t-neumann/slamdunk#75]
Hi Tobias, 

I was trying to run the slamdunk docker image using Singularity. In the past, I have been successful running both slamdunk and the alleyoop commands this way. But recently the utrrate has failed with the following error message:

```
Singularity> alleyoop utrrates -r /data/BatistaLab_NGS/SLAMseq/MH268_Christina_SLAM_Seq/MH268_PD_slam_Seq/GRCH38.p10_Annotations/GRCh38.p10.genome.fa -b /data/BatistaLab_NGS/SLAMseq/MH268_Christina_SLAM_Seq/MH268_PD_slam_Seq/GRCH38.p10_Annotations/SLAMbeds_v27_3utr.bed -o /data/BatistaLab_NGS/SLAMseq/MH268_Christina_SLAM_Seq/SLAMseq_output/gencode_v27/mut_gencodev27/alleyoop/ -t 4 /data/BatistaLab_NGS/SLAMseq/MH268_Christina_SLAM_Seq/SLAMseq_output/gencode_v27/mut_gencodev27/filter/*.bam
Running alleyoop utrrates for 12 files (4 threads)
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 600, in __call__
    return self.func(*args, **kwargs)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/alleyoop.py", line 174, in runStatsRatesUTR
    stats.statsComputeOverallRatesPerUTR(referenceFile, bam, minMQ, strictTCs, outputCSV, outputPDF, utrFile, maxReadLength, log)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/dunks/stats.py", line 528, in statsComputeOverallRatesPerUTR
    callR(getPlotter("globalRatePlotter") + " -f " + f.name + " -O " + outputPDF, log, dry=printOnly, verbose=verbose)
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/utils/misc.py", line 211, in callR
    raise RuntimeError("Error while executing command: \"" + cmd + "\"")
RuntimeError: Error while executing command: "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/plot/globalRatePlotter.R -f /tmp/tmp88do35nr -O /data/BatistaLab_NGS/SLAMseq/MH268_Christina_SLAM_Seq/SLAMseq_output/gencode_v27/mut_gencodev27/alleyoop/Mut_0hrA_S4_L008_R1_001.fastq_slamdunk_mapped_filtered_mutationrates_utr.pdf"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/slamdunk/bin/alleyoop", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/alleyoop.py", line 495, in run
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runStatsRatesUTR)(tid, args.bam[tid], referenceFile, minMQ, args.strictTCs, outputDirectory, args.bed, args.maxLength) for tid in range(0, len(args.bam)))
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 1016, in __call__
    self.retrieve()
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 908, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 554, in wrap_future_result
    return future.result(timeout=timeout)
  File "/opt/conda/envs/slamdunk/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/opt/conda/envs/slamdunk/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
RuntimeError: Error while executing command: "/opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/plot/globalRatePlotter.R -f /tmp/tmp88do35nr -O /data/BatistaLab_NGS/SLAMseq/MH268_Christina_SLAM_Seq/SLAMseq_output/gencode_v27/mut_gencodev27/alleyoop/Mut_0hrA_S4_L008_R1_001.fastq_slamdunk_mapped_filtered_mutationrates_utr.pdf"
```

I tried to execute this command manually and got the following error:

```
Singularity> /opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/plot/globalRatePlotter.R -f /tmp/tmp88do35nr -O /data/BatistaLab_NGS/SLAMseq/MH268_Christina_SLAM_Seq/SLAMseq_output/gencode_v27/mut_gencodev27/alleyoop/Mut_0hrA_S4_L008_R1_001.fastq_slamdunk_mapped_filtered_mutationrates_utr.pdf
bash: /opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/plot/globalRatePlotter.R: Permission denied
```
It seems like this file is both owned by root and missing the executable permissions, which may be the cause of the error. 
```
Singularity> ls -l /opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/plot/globalRatePlotter.R
-rw-r--r-- 1 root root 7087 Mar 25 06:40 /opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/plot/globalRatePlotter.R
```
If I run the command manually through R, so that it doesn't need execute permissions, it appears to succeed. 

```
Singularity> Rscript /opt/conda/envs/slamdunk/lib/python3.7/site-packages/slamdunk/plot/globalRatePlotter.R -f /tmp/tmp88do35nr -O /data/BatistaLab_NGS/SLAMseq/MH268_Christina_SLAM_Seq/SLAMseq_output/gencode_v27/mut_gencodev27/alleyoop/Mut_0hrA_S4_L008_R1_001.fastq_slamdunk_mapped_filtered_mutationrates_utr.pdf
[1] "Sample: mut_0_rep1"
                 diff           lwr          upr        p adj
A>G-A>C  0.0395825066  0.0175400823  0.061624931 2.887971e-07
A>T-A>C -0.0401391095 -0.0621815338 -0.018096685 1.751381e-07
C>A-A>C  0.0417413877  0.0196989633  0.063783812 3.996892e-08
C>G-A>C -0.0327055757 -0.0547480001 -0.010663151 7.914454e-05
C>T-A>C  0.0622067897  0.0401643653  0.084249214 1.333378e-13
...
```

I'm not aware of anything different that I'm doing, but I'm also not sure why it was working previously and is giving me trouble now. Any help would be greatly appreciated!

**Comment by t-neumann** [comment]
Hi @FitzsimmonsCM 

is this only happening for the `alleyoop utrrates` command or also others?

Did you pull a new image recently? I release a new version just last week, but I was not aware of me touching anything in those sections.

**Comment by FitzsimmonsCM** [comment]
Hi Tobias, 

I cleared the cache for singularity and re-pulled the latest docker contain. I got similar error messages as above for the 3 modules I ran: rates, tccontext, and utrrates. 

When I re-pulled slamdunk v0.3.4 and ran utrrates in that version, the program completed successfully with no errors and generated the expected csv, log, and pdf files. 

Thanks,
Christina

**Comment by t-neumann** [comment]
Hi Christina,

did you pull the one from `tobneu/slamdunk` or the biocontainers one from bioconda?

Cheers

**Comment by FitzsimmonsCM** [comment]
Hi Tobias, 

In both cases I pulled the `tobneu/slamdunk` container.

Best,

**Comment by t-neumann** [comment]
I will look into this. 

I strongly suspect it has to do with the file system swap we had by IT. That affected a lot of file permissions and might have touched my Github repo along the way and propagated into the remote.

This is super annoying I gotta say - two months nothing but troubles with this.

Sorry for the inconvenience

**Comment by t-neumann** [comment]
In the meanwhile, could you just pick an older version? Like 0.4.1?

The newest contains solely bugfixes that should not affect any results.

**Comment by FitzsimmonsCM** [comment]
No worries. Thanks a bunch!

**Comment by t-neumann** [comment]
Rebuilt and fixed
