### ISSUE TITLE
error in SNP dunk

### ISSUE THREAD

**Issue by CharlotteAnne** [t-neumann/slamdunk#80]
Hi!
Great software, love all the docs and conda support .etc.
Running for the first time I am getting an error at the SNP step - any idea where this comes from?
Thanks!
Charlotte

Edit: maybe I should say, I used the conda install of slam dunk which gave me version 0.4.0

```
slamdunk all
Waiting 0.915 seconds
Running only job 39
Running slamDunk map for 1 files (8 threads)
.
Running slamDunk filter for 1 files (8 threads)
.

Running slamDunk SNP for 1 files (4.0 threads)
Traceback (most recent call last):
  File "/camp/home/capitac/miniconda3/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 808, in dispatch_one_batch
    tasks = self._ready_batches.get(block=False)
  File "/camp/home/capitac/miniconda3/envs/slamdunk/lib/python3.7/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/camp/home/capitac/miniconda3/envs/slamdunk/bin/slamdunk", line 10, in <module>
    sys.exit(run())
  File "/camp/home/capitac/miniconda3/envs/slamdunk/lib/python3.7/site-packages/slamdunk/slamdunk.py", line 478, in run
    runAll(args)
  File "/camp/home/capitac/miniconda3/envs/slamdunk/lib/python3.7/site-packages/slamdunk/slamdunk.py", line 297, in runAll
    results = Parallel(n_jobs=snpThread, verbose=verbose)(delayed(runSnp)(tid, referenceFile, minCov, minVarFreq, snpqual, dunkbufferIn[tid], dunkPath) for tid in range(0, len(samples)))
  File "/camp/home/capitac/miniconda3/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "/camp/home/capitac/miniconda3/envs/slamdunk/lib/python3.7/site-packages/joblib/parallel.py", line 819, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
ValueError: Stop argument for islice() must be None or an integer: 0 <= x <= sys.maxsize.
```

**Comment by CharlotteAnne** [comment]
Hello again!
Good news - I installed the latest version with pip 0.4.3 and this error was resolved. I suggest you update the bioconda version or change the recommendation in your documentation - at the moment bioconda install is recommended.
All best,
Charlotte

**Comment by t-neumann** [comment]
Hi Charlotte,

hm that is weird because as you correctly said that bug was fixed in version 0.4.3 which is also the latest version I have on bioconda. You got any clue why 0.4.0 was installed in your case - did you specify this version number during install?

Cheers,

Tobi

**Comment by CharlotteAnne** [comment]
Hi
I tried again - just running:
`conda create --name slamdunk -c bioconda slamdunk`
leads to using the old version:
`slamdunk           bioconda/noarch::slamdunk-0.4.0-py_0`
It must be set as a default somehow.
All best,
Charlotte

**Comment by t-neumann** [comment]
So if you try it without specifying the bioconda channel with `-c bioconda` it looks up the correct version:

```
conda create --name slamdunk slamdunk

  slamdunk           bioconda/noarch::slamdunk-0.4.3-py_0
```
