### ISSUE TITLE
missing DS tag

### ISSUE THREAD

**Issue by bobermayer** [t-neumann/slamdunk#98]
Hi,

this is related to #31 and #28 but appears in version 0.4.3 (installed via conda): `alleyoop utrrates` fails 

```
Running alleyoop utrrates for 8 files (1 threads)
[E::idx_find_and_load] Could not retrieve index file for 'slamdunk/map/7031_S1_L001_R1_001_trimmed.fq_slamdunk_mapped.bam'
[E::idx_find_and_load] Could not retrieve index file for 'slamdunk/map/7031_S1_L001_R1_001_trimmed.fq_slamdunk_mapped.bam'
Traceback (most recent call last):
  File "/fast/users/obermayb_c/scratch/miniconda/envs/slamdunk/bin/alleyoop", line 10, in <module>
    sys.exit(run())
  File "/fast/users/obermayb_c/scratch/miniconda/envs/slamdunk/lib/python3.9/site-packages/slamdunk/alleyoop.py", line 530, in run
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runStatsRatesUTR)(tid, args.bam[tid], referenceFile, minMQ, args.strictTCs, outputDirectory, args.bed, args.maxLength) for tid in range(0, len(args.bam)))
  File "/fast/users/obermayb_c/scratch/miniconda/envs/slamdunk/lib/python3.9/site-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/fast/users/obermayb_c/scratch/miniconda/envs/slamdunk/lib/python3.9/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/fast/users/obermayb_c/scratch/miniconda/envs/slamdunk/lib/python3.9/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/fast/users/obermayb_c/scratch/miniconda/envs/slamdunk/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/fast/users/obermayb_c/scratch/miniconda/envs/slamdunk/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/fast/users/obermayb_c/scratch/miniconda/envs/slamdunk/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/fast/users/obermayb_c/scratch/miniconda/envs/slamdunk/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/fast/users/obermayb_c/scratch/miniconda/envs/slamdunk/lib/python3.9/site-packages/slamdunk/alleyoop.py", line 180, in runStatsRatesUTR
    stats.statsComputeOverallRatesPerUTR(referenceFile, bam, minMQ, strictTCs, outputCSV, outputPDF, utrFile, maxReadLength, log)
  File "/fast/users/obermayb_c/scratch/miniconda/envs/slamdunk/lib/python3.9/site-packages/slamdunk/dunks/stats.py", line 335, in statsComputeOverallRatesPerUTR
    slamseqInfo = SlamSeqInfo(bam)
  File "/fast/users/obermayb_c/scratch/miniconda/envs/slamdunk/lib/python3.9/site-packages/slamdunk/utils/misc.py", line 67, in __init__
    DS = ast.literal_eval(getReadGroup(bam)['DS'])
KeyError: 'DS'
```
and indeed my bam files don't have the DS tag:
```
$ samtools view -H slamdunk/map/7031_S1_L001_R1_001_trimmed.fq_slamdunk_mapped.bam  
@HD	VN:1.0	SO:unsorted
@SQ	SN:chr1	LN:195471971
@SQ	SN:chr2	LN:182113224
@SQ	SN:chr3	LN:160039680
@SQ	SN:chr4	LN:156508116
@SQ	SN:chr5	LN:151834684
@SQ	SN:chr6	LN:149736546
@SQ	SN:chr7	LN:145441459
@SQ	SN:chr8	LN:129401213
@SQ	SN:chr9	LN:124595110
@SQ	SN:chr10	LN:130694993
@SQ	SN:chr11	LN:122082543
@SQ	SN:chr12	LN:120129022
@SQ	SN:chr13	LN:120421639
@SQ	SN:chr14	LN:124902244
@SQ	SN:chr15	LN:104043685
@SQ	SN:chr16	LN:98207768
@SQ	SN:chr17	LN:94987271
@SQ	SN:chr18	LN:90702639
@SQ	SN:chr19	LN:61431566
@SQ	SN:chrX	LN:171031299
@SQ	SN:chrY	LN:91744698
@SQ	SN:chrM	LN:16299
```

<details>
<summary>other contigs</summary>

```
@SQ	SN:KZ289080.1	LN:394982
@SQ	SN:KZ289081.1	LN:369973
@SQ	SN:GL456210.1	LN:169725
@SQ	SN:GL456211.1	LN:241735
@SQ	SN:GL456212.1	LN:153618
@SQ	SN:GL456213.1	LN:39340
@SQ	SN:GL456216.1	LN:66673
@SQ	SN:GL456219.1	LN:175968
@SQ	SN:GL456221.1	LN:206961
@SQ	SN:GL456233.1	LN:336933
@SQ	SN:GL456239.1	LN:40056
@SQ	SN:GL456350.1	LN:227966
@SQ	SN:GL456354.1	LN:195993
@SQ	SN:GL456359.1	LN:22974
@SQ	SN:GL456360.1	LN:31704
@SQ	SN:GL456366.1	LN:47073
@SQ	SN:GL456367.1	LN:42057
@SQ	SN:GL456368.1	LN:20208
@SQ	SN:GL456370.1	LN:26764
@SQ	SN:GL456372.1	LN:28664
@SQ	SN:GL456378.1	LN:31602
@SQ	SN:GL456379.1	LN:72385
@SQ	SN:GL456381.1	LN:25871
@SQ	SN:GL456382.1	LN:23158
@SQ	SN:GL456383.1	LN:38659
@SQ	SN:GL456385.1	LN:35240
@SQ	SN:GL456387.1	LN:24685
@SQ	SN:GL456389.1	LN:28772
@SQ	SN:GL456390.1	LN:24668
@SQ	SN:GL456392.1	LN:23629
@SQ	SN:GL456393.1	LN:55711
@SQ	SN:GL456394.1	LN:24323
@SQ	SN:GL456396.1	LN:21240
@SQ	SN:JH584292.1	LN:14945
@SQ	SN:JH584293.1	LN:207968
@SQ	SN:JH584294.1	LN:191905
@SQ	SN:JH584295.1	LN:1976
@SQ	SN:JH584296.1	LN:199368
@SQ	SN:JH584297.1	LN:205776
@SQ	SN:JH584298.1	LN:184189
@SQ	SN:JH584299.1	LN:953012
@SQ	SN:JH584300.1	LN:182347
@SQ	SN:JH584301.1	LN:259875
@SQ	SN:JH584302.1	LN:155838
@SQ	SN:JH584303.1	LN:158099
@SQ	SN:JH584304.1	LN:114452
@SQ	SN:KZ289092.1	LN:460895
@SQ	SN:KQ030490.1	LN:120154
@SQ	SN:KB469738.3	LN:210641
@SQ	SN:JH792830.1	LN:246751
@SQ	SN:KV575237.1	LN:1224174
@SQ	SN:KK082442.1	LN:154766
@SQ	SN:KV575240.1	LN:171859
@SQ	SN:KV575235.1	LN:195735
@SQ	SN:KZ289088.1	LN:328684
@SQ	SN:KV575239.1	LN:71460
@SQ	SN:KQ030495.1	LN:490000
@SQ	SN:KV575238.1	LN:414410
@SQ	SN:KZ289082.1	LN:111720
@SQ	SN:KV575234.1	LN:686942
@SQ	SN:KZ289072.1	LN:425386
@SQ	SN:KQ030485.1	LN:185548
@SQ	SN:KQ030486.1	LN:399265
@SQ	SN:KQ030487.1	LN:316842
@SQ	SN:KZ289070.1	LN:378870
@SQ	SN:KZ289084.1	LN:283434
@SQ	SN:KZ289085.1	LN:380404
@SQ	SN:KZ289093.1	LN:245130
@SQ	SN:KZ289094.1	LN:155470
@SQ	SN:KZ289095.1	LN:305464
@SQ	SN:KZ289090.1	LN:263917
@SQ	SN:KZ289091.1	LN:448905
@SQ	SN:KZ289065.1	LN:171653
@SQ	SN:KZ289064.1	LN:117769
@SQ	SN:KB469739.1	LN:331111
@SQ	SN:KB469741.2	LN:505876
@SQ	SN:JH792829.1	LN:352455
@SQ	SN:KV575236.1	LN:166096
@SQ	SN:KV575233.1	LN:266016
@SQ	SN:JH792826.1	LN:368286
@SQ	SN:KZ289071.1	LN:355613
@SQ	SN:JH792828.1	LN:473738
@SQ	SN:KZ289083.1	LN:66290
@SQ	SN:KB469740.1	LN:316140
@SQ	SN:KZ289087.1	LN:253113
@SQ	SN:KZ289089.1	LN:662433
@SQ	SN:JH792832.1	LN:544189
@SQ	SN:JH792833.1	LN:221588
@SQ	SN:JH792827.1	LN:205713
@SQ	SN:JH792834.1	LN:331480
@SQ	SN:JH792831.2	LN:203377
@SQ	SN:KB469742.1	LN:1059955
@SQ	SN:KZ289067.1	LN:583977
@SQ	SN:KQ030484.1	LN:214957
@SQ	SN:KQ030494.1	LN:506812
@SQ	SN:KQ030496.1	LN:260447
@SQ	SN:KQ030497.1	LN:219721
@SQ	SN:KQ030492.1	LN:166012
@SQ	SN:KQ030493.2	LN:423369
@SQ	SN:KQ030491.1	LN:129865
@SQ	SN:KQ030488.1	LN:45901
@SQ	SN:KQ030489.1	LN:188269
@SQ	SN:KV575232.1	LN:200008
@SQ	SN:KV575241.1	LN:211337
@SQ	SN:KZ289076.1	LN:318915
@SQ	SN:KZ289068.1	LN:532572
@SQ	SN:KZ289069.1	LN:709099
@SQ	SN:KV575242.1	LN:299789
@SQ	SN:KZ289086.1	LN:542789
@SQ	SN:KZ289066.1	LN:339234
@SQ	SN:KK082441.1	LN:456798
@SQ	SN:KZ289077.1	LN:186144
@SQ	SN:KZ289078.1	LN:390920
@SQ	SN:KZ289079.1	LN:368967
@SQ	SN:KZ289073.1	LN:215264
@SQ	SN:KZ289074.1	LN:394026
@SQ	SN:KZ289075.1	LN:322221
```

</details>

```
@PG	ID:ngm	PN:ngm	VN:0.5.5	CL:" --affine 0 --argos_min_score 0 --bin_size 2 --block_multiplier 2 --broken_pairs 0 --bs_cutoff 6 --bs_mapping 0 --cpu_threads 8 --dualstrand 1 --fast 0 --fast_pairing 0 --force_rlength_check 0 --format 1 --gap_extend_penalty 5 --gap_read_penalty 20 --gap_ref_penalty 20 --hard_clip 0 --keep_tags 0 --kmer 13 --kmer_min 0 --kmer_skip 2 --local 1 --match_bonus 10 --match_bonus_tc 2 --match_bonus_tt 10 --max_cmrs 2147483647 --max_equal 1 --max_insert_size 1000 --max_polya 4 --max_read_length 0 --min_identity 0.650000 --min_insert_size 0 --min_mq 0 --min_residues 0.500000 --min_score 0.000000 --mismatch_penalty 15 --mode 0 --no_progress 1 --no_unal 0 --ocl_threads 1 --output slamdunk/map/7031_S1_L001_R1_001_trimmed.fq_slamdunk_mapped.sam --overwrite 1 --pair_score_cutoff 0.900000 --paired 0 --parse_all 1 --pe_delimiter / --qry DMSO1/7031_S1_L001_R1_001_trimmed.fq.gz --qry_count -1 --qry_start 0 --ref annotation/GRCm38.p6.genome.fa --ref_mode -1 --rg_id 0 --rg_sm 7031_S1_L001_R1_001_trimmed.fq:pulse:0 --sensitive 0 --silent_clip 0 --skip_mate_check 0 --skip_save 0 --slam_seq 2 --step_count 4 --strata 0 --topn 1 --trim5 12 --update_check 0 --very_fast 0 --very_sensitive 0"
@PG	ID:samtools	PN:samtools	PP:ngm	VN:1.12	CL:samtools view -@ 8 -Sb -o slamdunk/map/7031_S1_L001_R1_001_trimmed.fq_slamdunk_mapped.bam slamdunk/map/7031_S1_L001_R1_001_trimmed.fq_slamdunk_mapped.sam
@PG	ID:samtools.1	PN:samtools	PP:samtools	VN:1.12	CL:samtools view -H slamdunk/map/7031_S1_L001_R1_001_trimmed.fq_slamdunk_mapped.bam
@RG	ID:0	SM:7031_S1_L001_R1_001_trimmed.fq:pulse:0
```
I ran `slamdunk` on trimmed fastq files (TrimGalore).

any ideas? help greatly appreciated!

**Comment by t-neumann** [comment]
Hi - you should run all commands on the filtered bam files in the `filter` folder. Then everything should work.

**Comment by bobermayer** [comment]
yes, great, this works. thanks a lot
