### ISSUE TITLE
analysing HISAT-3N bam files

### ISSUE THREAD

**Issue by pillailab** [t-neumann/slamdunk#99]
Hi, 
I would like to see if bam files from HISAT-3N can be used for steps downstream of map dunk. I am getting stuck at the filter dunk due to bam-tag incompatibility. 

Running slamDunk filter for 1 files (8 threads)
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/slamdunk/slamdunk.py", line 170, in runFilter
    filter.Filter(bam, outputBAM, getLogFile(outputLOG), bed, mq, minIdentity, maxNM, printOnly, verbose)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/slamdunk/dunks/filter.py", line 246, in Filter
    if(float(read.get_tag("XI")) < minIdentity):
  File "pysam/libcalignedsegment.pyx", line 2399, in pysam.libcalignedsegment.AlignedSegment.get_tag
  File "pysam/libcalignedsegment.pyx", line 2438, in pysam.libcalignedsegment.AlignedSegment.get_tag
KeyError: "tag 'XI' not present"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/bin/slamdunk", line 10, in <module>
    sys.exit(run())
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/slamdunk/slamdunk.py", line 485, in run
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runFilter)(tid, args.bam[tid], args.bed, args.mq, args.identity, args.nm, outputDirectory) for tid in range(0, len(args.bam)))
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
KeyError: "tag 'XI' not present"

Any suggestion as to how one may adapt it to HISAT-3N files ?
Thank you,
Manoj

**Comment by t-neumann** [comment]
Hi Manoj,

HISAT-3N should in principal bring all the relevant filter steps and tags that you could directly move on with the `snp` and `count` step.

**Comment by pillailab** [comment]
Thank you, I did generate vcf files without issues, but when I ran the count step, it asked me to run the filter again: Running slamDunk tcount for 1 files (8 threads)
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/slamdunk/slamdunk.py", line 202, in runCount
    tcounter.computeTconversions(ref, bed, inputSNP, bam, maxLength, minQual, outputCSV, outputBedgraphPlus, outputBedgraphMinus, conversionThreshold, log)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/slamdunk/dunks/tcounter.py", line 129, in computeTconversions
    sampleInfo = getSampleInfo(bam)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/slamdunk/utils/misc.py", line 239, in getSampleInfo
    sampleInfo = getReadGroup(bam)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/slamdunk/utils/misc.py", line 236, in getReadGroup
    raise RuntimeError("Could not get mapped/unmapped/filtered read counts from BAM file. RG is missing. Please rerun slamdunk filter.")
RuntimeError: Could not get mapped/unmapped/filtered read counts from BAM file. RG is missing. Please rerun slamdunk filter.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/bin/slamdunk", line 10, in <module>
    sys.exit(run())
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/slamdunk/slamdunk.py", line 516, in run
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runCount)(tid, args.bam[tid], args.ref, args.bed, args.maxLength, args.minQual, args.conversionThreshold, outputDirectory, snpDirectory, vcfFile) for tid in range(0, len(args.bam)))
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
RuntimeError: Could not get mapped/unmapped/filtered read counts from BAM file. RG is missing. Please rerun slamdunk filter.

I understand that "read groups" are missing; can you please elaborate what tags should be in the bam for count dunk to run ?
thanks,
Manoj

**Comment by t-neumann** [comment]
Ah yes that's true you need a read group tag with the following fields (used for efficient metric calculations):

`@RG	ID:0	SM:DMSO:pulse:0	DS:{'sequenced':31615691,'mapped':30013901,'filtered':23556432,'mqfiltered':22906087,'idfiltered':535873,'nmfiltered':0,'multimapper':0,'dedup':0,'snps':0,'annotation':'','annotationmd5':''}`

You need at least to provide

`Name, ID, Type, Time`

specified in the SM part and also the number of filtered reads in the `filtered` part of the `DS` string for proper RPM normalization. Then indeed it should work.

**Comment by pillailab** [comment]
Thank you, and sorry for the delay ( we had to generate new sequencing files). I am running the following to add the tags but still getting errors

samtools addreplacerg -@ 8 -r ID:sampleID -r SM:sampleName:pulse:0 -r DS:'{"sequenced":187630418,"mapped":102259633,"filtered":0,"mqfiltered":0,"idfiltered":0,"nmfiltered":0,"multimapper":0,"dedup":0,"snps":0}' \
        -o MPR110.hisat-3n.RG.bam MPR110.hisat-3n.bam
        samtools index "$b".hisat-3n.RG.bam
        slamdunk count -r $fasta \
                -o $dir/slamdunk/count \
                -s $dir/slamdunk/snp \
                -t 8 -l 150 \
                -b $bed \
                "$b".hisat-3n.RG.bam
Should  I be adding speicfic numbers for the DS:{} as you suggested ? generated from samtools flagstat or similar ?
Thank you for the help,
Manoj

**Comment by pillailab** [comment]
With that script, this is the output 👍 Running slamDunk tcount for 1 files (8 threads)
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/slamdunk/slamdunk.py", line 202, in runCount
    tcounter.computeTconversions(ref, bed, inputSNP, bam, maxLength, minQual, outputCSV, outputBedgraphPlus, outputBedgraphMinus, conversionThreshold, log)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/slamdunk/dunks/tcounter.py", line 157, in computeTconversions
    raise RuntimeError("Wrong filtered BAM file version detected (" + testFile.bamVersion + "). Expected version " + __bam_version__ + ". Please rerun slamdunk filter.")
RuntimeError: Wrong filtered BAM file version detected (None). Expected version 3. Please rerun slamdunk filter.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/bin/slamdunk", line 10, in <module>
    sys.exit(run())
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/slamdunk/slamdunk.py", line 516, in run
    results = Parallel(n_jobs=n, verbose=verbose)(delayed(runCount)(tid, args.bam[tid], args.ref, args.bed, args.maxLength, args.minQual, args.conversionThreshold, outputDirectory, snpDirectory, vcfFile) for tid in range(0, len(args.bam)))
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/gpfs/ysm/project/pillai/mp758/conda_envs/slamdunk/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
RuntimeError: Wrong filtered BAM file version detected (None). Expected version 3. Please rerun slamdunk filter.
